### ISSUE TITLE
breaks the desktop in gnome 43 and Fedora 37

### ISSUE THREAD

**Issue by bjt-user** [fthx/no-overview#17]
On Fedora 37 workstation and gnome 43.2 this extension is very buggy.
When you hit the super key you can't use the search and you can't even get out of the overview anymore.
The only thing you can do then is to log out and then disable this extension.

Maybe it is a combination of the built-in gnome-extentions I am using:
```
$ gnome-extensions list --enabled
apps-menu@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
```

I used this extension in Fedora 36 for a couple of month and it worked fine there, but in Fedora 37 it is definately not stable.

**Comment by linux2299** [comment]
This problem also occurs in Ubuntu 22.04 which uses GNOME 42.5. And I think it only happens when the "window-list" extension is enabled.

The problem is that pressing the super key takes you into the overview, but pressing it again does not take you out of the overview. Clicking the "activities" menu button in the top left corner does still work, though.

**Comment by bdwakefield** [comment]
I responded on the other issue related to being stuck in Overview; but it does look like it is some interaction between this extension and the window list one.

Fedora 38
6.2.15-300.fc38.x86_64
GS 44.1

**Comment by fthx** [comment]
Please use the other bug thread.
And please test the issue without any other extension enabled.
