### ISSUE TITLE
autostart application not working

### ISSUE THREAD

**Issue by takala-jp** [fthx/no-overview#7]
Hi there, thank you for adding this functionality. 

It looks like enabling this extension stops applications in `~/.config/autostart/` from actually starting up when logging in. Gnome version 40.4.0 with no other extensions enabled.

**Comment by fthx** [comment]
Hi,

Just tested this now in my Ubuntu 21.10 VM with gnome-calculator.
I don't experience this issue.

So maybe it's a false positive. I don't have any other complain from another user (and a lot do use this ext because autostarts).
I close this now. If you have some adds about your distro/setup and still experience this, feel free to reopen.
